<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClassSessionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $class_sessions = [
            ['start_lesson' => '12:55:00', 'end_lesson' => '15:35:00', 'day_of_week' => '3', 'room_id' => 12, 'class_id' => 1],
            ['start_lesson' => '12:55:00', 'end_lesson' => '15:35:00', 'day_of_week' => '4', 'room_id' => 5, 'class_id' => 2],
            ['start_lesson' => '15:40:00', 'end_lesson' => '18:20:00', 'day_of_week' => '3', 'room_id' => 13, 'class_id' => 3],
            ['start_lesson' => '15:40:00', 'end_lesson' => '18:20:00', 'day_of_week' => '4', 'room_id' => 5, 'class_id' => 4],
            ['start_lesson' => '12:55:00', 'end_lesson' => '15:35:00', 'day_of_week' => '4', 'room_id' => 13, 'class_id' => 5],
            ['start_lesson' => '15:40:00', 'end_lesson' => '18:20:00', 'day_of_week' => '4', 'room_id' => 13, 'class_id' => 6],
            ['start_lesson' => '12:55:00', 'end_lesson' => '15:35:00', 'day_of_week' => '5', 'room_id' => 14, 'class_id' => 7],
            ['start_lesson' => '15:40:00', 'end_lesson' => '18:20:00', 'day_of_week' => '7', 'room_id' => 14, 'class_id' => 8],
            ['start_lesson' => '07:00:00', 'end_lesson' => '09:45:00', 'day_of_week' => '2', 'room_id' => 14, 'class_id' => 9],
            ['start_lesson' => '09:45:00', 'end_lesson' => '12:25:00', 'day_of_week' => '2', 'room_id' => 14, 'class_id' => 10],
            ['start_lesson' => '07:00:00', 'end_lesson' => '09:45:00', 'day_of_week' => '6', 'room_id' => 12, 'class_id' => 11],
            ['start_lesson' => '09:45:00', 'end_lesson' => '12:25:00', 'day_of_week' => '6', 'room_id' => 12, 'class_id' => 12],
            ['start_lesson' => '12:55:00', 'end_lesson' => '15:35:00', 'day_of_week' => '6', 'room_id' => 12, 'class_id' => 13],
            ['start_lesson' => '15:40:00', 'end_lesson' => '18:20:00', 'day_of_week' => '6', 'room_id' => 12, 'class_id' => 14],
            ['start_lesson' => '07:00:00', 'end_lesson' => '09:45:00', 'day_of_week' => '6', 'room_id' => 14, 'class_id' => 15],
            ['start_lesson' => '09:45:00', 'end_lesson' => '12:25:00', 'day_of_week' => '6', 'room_id' => 14, 'class_id' => 16],
            ['start_lesson' => '12:55:00', 'end_lesson' => '15:35:00', 'day_of_week' => '2', 'room_id' => 10, 'class_id' => 17],
            ['start_lesson' => '15:40:00', 'end_lesson' => '18:20:00', 'day_of_week' => '2', 'room_id' => 10, 'class_id' => 18],
            ['start_lesson' => '12:55:00', 'end_lesson' => '15:35:00', 'day_of_week' => '6', 'room_id' => 13, 'class_id' => 19],
            ['start_lesson' => '15:40:00', 'end_lesson' => '18:20:00', 'day_of_week' => '6', 'room_id' => 13, 'class_id' => 20],
            ['start_lesson' => '07:00:00', 'end_lesson' => '09:45:00', 'day_of_week' => '6', 'room_id' => 2, 'class_id' => 21],
            ['start_lesson' => '09:45:00', 'end_lesson' => '12:25:00', 'day_of_week' => '6', 'room_id' => 2, 'class_id' => 22],
            ['start_lesson' => '07:00:00', 'end_lesson' => '09:45:00', 'day_of_week' => '2', 'room_id' => 9, 'class_id' => 23],
            ['start_lesson' => '09:45:00', 'end_lesson' => '12:25:00', 'day_of_week' => '2', 'room_id' => 9, 'class_id' => 24],
            ['start_lesson' => '12:55:00', 'end_lesson' => '15:35:00', 'day_of_week' => '3', 'room_id' => 14, 'class_id' => 25],
            ['start_lesson' => '15:40:00', 'end_lesson' => '18:20:00', 'day_of_week' => '3', 'room_id' => 14, 'class_id' => 26],
            ['start_lesson' => '12:55:00', 'end_lesson' => '15:35:00', 'day_of_week' => '4', 'room_id' => 6, 'class_id' => 27],
            ['start_lesson' => '15:40:00', 'end_lesson' => '18:20:00', 'day_of_week' => '4', 'room_id' => 6, 'class_id' => 28],
        ];

        DB::table('class_sessions')->insert($class_sessions);

        $class_session_lessons = [
            ['session_id' => 1, 'lesson_id' => 7],
            ['session_id' => 1, 'lesson_id' => 8],
            ['session_id' => 1, 'lesson_id' => 9],
            ['session_id' => 2, 'lesson_id' => 7],
            ['session_id' => 2, 'lesson_id' => 8],
            ['session_id' => 2, 'lesson_id' => 9],
            ['session_id' => 3, 'lesson_id' => 10],
            ['session_id' => 3, 'lesson_id' => 11],
            ['session_id' => 3, 'lesson_id' => 12],
            ['session_id' => 4, 'lesson_id' => 10],
            ['session_id' => 4, 'lesson_id' => 11],
            ['session_id' => 4, 'lesson_id' => 12],
            ['session_id' => 5, 'lesson_id' => 7],
            ['session_id' => 5, 'lesson_id' => 8],
            ['session_id' => 5, 'lesson_id' => 9],
            ['session_id' => 6, 'lesson_id' => 10],
            ['session_id' => 6, 'lesson_id' => 11],
            ['session_id' => 6, 'lesson_id' => 12],
            ['session_id' => 7, 'lesson_id' => 7],
            ['session_id' => 7, 'lesson_id' => 8],
            ['session_id' => 7, 'lesson_id' => 9],
            ['session_id' => 8, 'lesson_id' => 10],
            ['session_id' => 8, 'lesson_id' => 11],
            ['session_id' => 8, 'lesson_id' => 12],
            ['session_id' => 9, 'lesson_id' => 1],
            ['session_id' => 9, 'lesson_id' => 2],
            ['session_id' => 9, 'lesson_id' => 3],
            ['session_id' => 10, 'lesson_id' => 4],
            ['session_id' => 10, 'lesson_id' => 5],
            ['session_id' => 10, 'lesson_id' => 6],
            ['session_id' => 11, 'lesson_id' => 1],
            ['session_id' => 11, 'lesson_id' => 2],
            ['session_id' => 11, 'lesson_id' => 3],
            ['session_id' => 12, 'lesson_id' => 4],
            ['session_id' => 12, 'lesson_id' => 5],
            ['session_id' => 12, 'lesson_id' => 6],
            ['session_id' => 13, 'lesson_id' => 7],
            ['session_id' => 13, 'lesson_id' => 8],
            ['session_id' => 13, 'lesson_id' => 9],
            ['session_id' => 14, 'lesson_id' => 10],
            ['session_id' => 14, 'lesson_id' => 11],
            ['session_id' => 14, 'lesson_id' => 12],
            ['session_id' => 15, 'lesson_id' => 1],
            ['session_id' => 15, 'lesson_id' => 2],
            ['session_id' => 15, 'lesson_id' => 3],
            ['session_id' => 16, 'lesson_id' => 4],
            ['session_id' => 16, 'lesson_id' => 5],
            ['session_id' => 16, 'lesson_id' => 6],
            ['session_id' => 17, 'lesson_id' => 7],
            ['session_id' => 17, 'lesson_id' => 8],
            ['session_id' => 17, 'lesson_id' => 9],
            ['session_id' => 18, 'lesson_id' => 10],
            ['session_id' => 18, 'lesson_id' => 11],
            ['session_id' => 18, 'lesson_id' => 12],
            ['session_id' => 19, 'lesson_id' => 7],
            ['session_id' => 19, 'lesson_id' => 8],
            ['session_id' => 19, 'lesson_id' => 9],
            ['session_id' => 20, 'lesson_id' => 10],
            ['session_id' => 20, 'lesson_id' => 11],
            ['session_id' => 20, 'lesson_id' => 12],
            ['session_id' => 21, 'lesson_id' => 1],
            ['session_id' => 21, 'lesson_id' => 2],
            ['session_id' => 21, 'lesson_id' => 3],
            ['session_id' => 22, 'lesson_id' => 4],
            ['session_id' => 22, 'lesson_id' => 5],
            ['session_id' => 22, 'lesson_id' => 6],
            ['session_id' => 23, 'lesson_id' => 1],
            ['session_id' => 23, 'lesson_id' => 2],
            ['session_id' => 23, 'lesson_id' => 3],
            ['session_id' => 24, 'lesson_id' => 4],
            ['session_id' => 24, 'lesson_id' => 5],
            ['session_id' => 24, 'lesson_id' => 6],
            ['session_id' => 25, 'lesson_id' => 7],
            ['session_id' => 25, 'lesson_id' => 8],
            ['session_id' => 25, 'lesson_id' => 9],
            ['session_id' => 26, 'lesson_id' => 10],
            ['session_id' => 26, 'lesson_id' => 11],
            ['session_id' => 26, 'lesson_id' => 12],
            ['session_id' => 27, 'lesson_id' => 7],
            ['session_id' => 27, 'lesson_id' => 8],
            ['session_id' => 27, 'lesson_id' => 9],
            ['session_id' => 28, 'lesson_id' => 10],
            ['session_id' => 28, 'lesson_id' => 11],
            ['session_id' => 28, 'lesson_id' => 12],
        ];

        DB::table('class_session_lesson')->insert($class_session_lessons);
    }
}
